### ISSUE TITLE
Add GitHub Actions workflow for automatic tag builds

### ISSUE THREAD

**Issue by wisarmy** [wisarmy/fingerprint#1]
## Overview
Add a GitHub Actions workflow to automatically build and package the project when a new tag is created.

## Requirements
- Trigger workflow when a new tag is pushed
- Build the project
- Create a release with the built artifacts
- Attach the built artifacts to the release

## Implementation Details
Create a new workflow file `.github/workflows/release.yml` with the following configuration:

```yaml
name: Release Build

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        # Add build commands here
        # Example:
        # make build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          # Specify build artifacts to include
          # Example:
          # dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Tasks
- [ ] Create workflow file
- [ ] Configure build steps based on project requirements
- [ ] Test workflow by creating a test tag
- [ ] Document release process in README.md

## Notes
- The workflow will need to be customized based on the project's build requirements
- Make sure to specify the correct build artifacts to be included in the release
